<?php

namespace common\models\tables;

use Symfony\Component\DomCrawler\Image;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;
use common\models\tables\ImageUpload;


/**
 * This is the model class for table "tasks".
 *
 * @property int $id
 * @property string $name
 * @property string $date
 * @property string $description
 * @property int $user_id
 * @property string $image
 *
 * @property Users $user
 */
class Tasks extends ActiveRecord
{

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                /*'createdAtAttribute' => 'create_time',
                'updatedAtAttribute' => 'update_time',*/
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * Поиск по диапазону дат, начальная дата
     * @var string
     */

    public $createdFrom;

    /**
     * Поиск по диапазону дат, конечная дата
     * @var string
     */

    public $createdTo;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tasks';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'description'], 'required'],
            [['date'], 'default', 'value' => date('Y-m-d:H:i:s')],
            [['date'], 'compare', 'compareValue' => date('Y-m-d'), 'operator' => '>='],
            [['user_id'], 'integer'],
            [['name'], 'string', 'max' => 128],
            [['description'], 'string', 'max' => 1024],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'date' => 'Date',
            'image' => 'Image',
            'description' => 'Description',
            'user_id' => 'User ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'user_id']);
    }

    public static function getUsers($id)
    {
        return static::find()
            ->where(['user_id' => $id])
            ->all();
    }

    public static function getTaskCurrentMonth($month, $id)
    {
        return static::find()
            ->where(["MONTH(date)" => $month, 'user_id' => $id]);
    }

    public function saveImage($filename)
    {

        $this->image = $filename;

        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->image) ? '/uploads' . $this->image : '/no-image.png';
    }

    /**
     *
     */
    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
